### ISSUE TITLE
MVC core adhoc samples/ views ?

### ISSUE THREAD

**Issue by weedkiller** [easyquery/DotNetSamples#20]
Hello, I was trying the update, do you have sample ASP Core MVC views for .NET core 5 on adhoc querying, functions, filtering or google search like your website page

**Comment by korzh** [comment]
Hello,

All our [samples that work with Razor Pages](https://github.com/easyquery/DotNetSamples/tree/master/AspNetCore/Razor-Mvc) will work with MVC views with a small modification. You just need to split a Razor page on a corresponding controller/view pair. All other parts of the sample will remain the same.

**Comment by korzh** [comment]
As for Google Search, do you mean our [Advangle](http://advangle.com/) webapp? If yes, we didn't publish its source code since it was created quite a long time ago, and with a very old version of EasyQuery. We can restore it if we get a request about that from one of our license owners.

**Comment by weedkiller** [comment]
Too bad, I really like that use case, the main appeal was that it went beyond sql and illustrated yourself as different from other and query builders.

If you decide to share that sample again I have some input for you where it could be valuable product.
