### ISSUE TITLE
Formula builder

### ISSUE THREAD

**Issue by weedkiller** [easyquery/DotNetSamples#21]
The one particular application which may not seem obvious to you is a formula builder we often use data queries and then supplement them with the formula for an insurance calculation. 

I have been trying to work out something with your samples and it does not seem obvious to me on how to connect something like that is there a chance you can consider a formula builder on top of your query builder as a gui

**Comment by weedkiller** [comment]
Latest version does not build 

![image](https://user-images.githubusercontent.com/21086190/115736684-7711bc80-a359-11eb-8974-07464c8f910a.png)

**Comment by korzh** [comment]
What project are you trying to build?

**Comment by weedkiller** [comment]
ASP core samples, but I cant see any pages/ mvc view missing its still now help
