### ISSUE TITLE
.NET 6 with EF core 6 on VS 2022

### ISSUE THREAD

**Issue by fasteddys** [easyquery/DotNetSamples#23]
Hi can you update this please to target Core .net 6   

MS announced net 2 and 3.1 are not longer supported 

https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/#:~:text=NET%20Core%202.1%20will%20be,technical%20support%20for%20this%20version.

**Comment by korzh** [comment]
.NET 6 support is already included in the upcoming version 1.4.0 that is already [available as a BETA](https://www.nuget.org/packages/EasyData.AspNetCore/) (version 1.4.0-beta01)

As for .NET Core 2.1, we never targeted it directly. EasyData packages target .NET Standard 2.0 or 2.1 and will continue to do it, so they can be used in as many kinds of projects as possible.

**Comment by korzh** [comment]
Closing the issue since the request is done already.

**Comment by korzh** [comment]
Closed by mistake (it was supposed to be another issue). Reopened.

**Comment by fasteddys** [comment]
Thanks, my laptop with win 11, does not support the old .NET core :)

**Comment by fasteddys** [comment]
Hello, I tried the latest samples again, and wanted to let you know that your latest dlls from nugets release `is still showing wrong targets`, my Win 11 dev computer only has .NET 6 LTS and I still have this issue, to run the trial samples I had to force an install netstandard 2.0  Can you please release .NET core 6 target

<img width="596" alt="image" src="https://user-images.githubusercontent.com/96149622/170853127-e2855694-6550-4c5e-8a20-e952dbdd62de.png">

Sometimes I get this error.. 
![image](https://user-images.githubusercontent.com/96149622/170853177-e3a6d180-9bab-4c3e-8a24-19e33b60d05b.png)

**Comment by korzh** [comment]
That's really strange since the .NET documentation says it must be supported without any problem:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

We need to investigate this more

**Comment by korzh** [comment]
@melnalex Could you please try to reproduce this problem on a clean machine (for example a virtual Win11 machine on Azure)?

**Comment by fasteddys** [comment]
Hello Korzh, I am so sorry, I am not sure what was going on. It took me a good while when I was playing around with it. So I cleaned everything, tried it on a different machine and it ran fine. So, I am scratching my head here, I don't understand why it was showing old .NET 2 targets.

And today I deleted everything and got the latest samples, to my surprise the ASP Core MVC _views_ project is completely missing, also you used to have permissions for an authorized user, which was greatly convenient, is that coming back with any update. Or, was it moved somewhere renamed to something else? 

On the data permissions, maybe this is out of scope, but if you can show how an admin, can change the role/or add claim to let user see only their regional data, that can be a differentiator, since you have some reports also.

Also I see its sql, but I like your approach and wondering how this work on a NoSql like a Mongo /Redis or Neo4j?
